### ISSUE TITLE
Conceptual question on RNA-Seq 

### ISSUE THREAD

**Issue by sparthib** [HKU-BAL/Clair3-RNA#2]
Hi there, could I use Clair3-RNA to haplotype resolve my RNA-Seq reads at the isoform level? i.e. could I map my reads to a transcriptome instead of a genome and obtain haplotype resolution.

Thanks,
Sowmya

**Comment by zhengzhenxian** [comment]
Hi @sparthib,

Yes, you could use a transcriptome instead of a genome for RNA variant detection. Kindly let us know if you encounter any issue for this.

To acquire haplotype information, you might need whatshap [phase](https://whatshap.readthedocs.io/en/latest/guide.html#subcommands) and [haplotag](https://whatshap.readthedocs.io/en/latest/guide.html#subcommands) submodule to phase the Clair3-RNA called variant and then haplotag the BAM.

Zhenxian
